"""Bash completion script generator."""


def generate_bash_completion() -> str:
    """Generate bash completion script for gw."""
    return '''# Bash completion for gw (Grove Wrap)
# Generated by gw completion bash
# Add to ~/.bashrc or source directly

_gw_completion() {
    local cur prev words cword
    _init_completion || return

    # Top-level commands
    local commands="db tenant cache secret kv r2 do flag backup deploy logs email auth status health bindings git gh dev test build check lint ci packages doctor whoami history"

    # Handle completions based on position
    case "${cword}" in
        1)
            # First argument - top level commands
            COMPREPLY=($(compgen -W "${commands}" -- "${cur}"))
            return 0
            ;;
        *)
            # Subcommands based on first argument
            case "${words[1]}" in
                db)
                    local db_cmds="list tables schema query tenant"
                    if [[ ${cword} -eq 2 ]]; then
                        COMPREPLY=($(compgen -W "${db_cmds}" -- "${cur}"))
                    fi
                    ;;
                tenant)
                    local tenant_cmds="lookup stats list"
                    if [[ ${cword} -eq 2 ]]; then
                        COMPREPLY=($(compgen -W "${tenant_cmds}" -- "${cur}"))
                    fi
                    ;;
                cache)
                    local cache_cmds="list purge stats"
                    if [[ ${cword} -eq 2 ]]; then
                        COMPREPLY=($(compgen -W "${cache_cmds}" -- "${cur}"))
                    fi
                    ;;
                secret)
                    local secret_cmds="init set list delete apply sync exists"
                    if [[ ${cword} -eq 2 ]]; then
                        COMPREPLY=($(compgen -W "${secret_cmds}" -- "${cur}"))
                    fi
                    ;;
                kv)
                    local kv_cmds="list keys get put delete"
                    if [[ ${cword} -eq 2 ]]; then
                        COMPREPLY=($(compgen -W "${kv_cmds}" -- "${cur}"))
                    fi
                    ;;
                r2)
                    local r2_cmds="list ls get put rm"
                    if [[ ${cword} -eq 2 ]]; then
                        COMPREPLY=($(compgen -W "${r2_cmds}" -- "${cur}"))
                    fi
                    ;;
                git)
                    local git_cmds="status log diff blame show add commit push branch stash switch save sync wip undo amend reset rebase merge"
                    if [[ ${cword} -eq 2 ]]; then
                        COMPREPLY=($(compgen -W "${git_cmds}" -- "${cur}"))
                    fi
                    ;;
                gh)
                    local gh_cmds="pr issue run api rate-limit"
                    if [[ ${cword} -eq 2 ]]; then
                        COMPREPLY=($(compgen -W "${gh_cmds}" -- "${cur}"))
                    fi
                    # Handle nested subcommands
                    case "${words[2]}" in
                        pr)
                            local pr_cmds="list view create checkout comment merge close"
                            if [[ ${cword} -eq 3 ]]; then
                                COMPREPLY=($(compgen -W "${pr_cmds}" -- "${cur}"))
                            fi
                            ;;
                        issue)
                            local issue_cmds="list view create comment close"
                            if [[ ${cword} -eq 3 ]]; then
                                COMPREPLY=($(compgen -W "${issue_cmds}" -- "${cur}"))
                            fi
                            ;;
                        run)
                            local run_cmds="list view rerun cancel"
                            if [[ ${cword} -eq 3 ]]; then
                                COMPREPLY=($(compgen -W "${run_cmds}" -- "${cur}"))
                            fi
                            ;;
                    esac
                    ;;
                dev)
                    local dev_cmds="start stop restart logs status"
                    if [[ ${cword} -eq 2 ]]; then
                        COMPREPLY=($(compgen -W "${dev_cmds}" -- "${cur}"))
                    fi
                    ;;
                backup)
                    local backup_cmds="list create restore download"
                    if [[ ${cword} -eq 2 ]]; then
                        COMPREPLY=($(compgen -W "${backup_cmds}" -- "${cur}"))
                    fi
                    ;;
                flag)
                    local flag_cmds="list get enable disable"
                    if [[ ${cword} -eq 2 ]]; then
                        COMPREPLY=($(compgen -W "${flag_cmds}" -- "${cur}"))
                    fi
                    ;;
                auth)
                    local auth_cmds="check login client"
                    if [[ ${cword} -eq 2 ]]; then
                        COMPREPLY=($(compgen -W "${auth_cmds}" -- "${cur}"))
                    fi
                    case "${words[2]}" in
                        client)
                            local client_cmds="create list info rotate delete setup"
                            if [[ ${cword} -eq 3 ]]; then
                                COMPREPLY=($(compgen -W "${client_cmds}" -- "${cur}"))
                            fi
                            ;;
                    esac
                    ;;
                history)
                    local history_cmds="list search show run clear"
                    if [[ ${cword} -eq 2 ]]; then
                        COMPREPLY=($(compgen -W "${history_cmds}" -- "${cur}"))
                    fi
                    ;;
                packages)
                    local pkg_cmds="list info current"
                    if [[ ${cword} -eq 2 ]]; then
                        COMPREPLY=($(compgen -W "${pkg_cmds}" -- "${cur}"))
                    fi
                    ;;
            esac
            ;;
    esac

    # Complete options
    if [[ "${cur}" == -* ]]; then
        local opts="--help --json --write --force --verbose --dry-run"
        COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
    fi

    return 0
}

complete -F _gw_completion gw
'''
