"""Fish completion script generator."""


def generate_fish_completion() -> str:
    """Generate fish completion script for gw."""
    return '''# Fish completion for gw (Grove Wrap)
# Generated by gw completion fish
# Save to ~/.config/fish/completions/gw.fish

# Disable file completion by default
complete -c gw -f

# Global options
complete -c gw -l help -d "Show help"
complete -c gw -l json -d "Output as JSON"
complete -c gw -l write -d "Enable write operations"
complete -c gw -l force -d "Force dangerous operations"
complete -c gw -s v -l verbose -d "Verbose output"
complete -c gw -l dry-run -d "Preview without executing"

# Top-level commands
complete -c gw -n "__fish_use_subcommand" -a db -d "Database operations"
complete -c gw -n "__fish_use_subcommand" -a tenant -d "Tenant management"
complete -c gw -n "__fish_use_subcommand" -a cache -d "Cache management"
complete -c gw -n "__fish_use_subcommand" -a secret -d "Secrets vault"
complete -c gw -n "__fish_use_subcommand" -a kv -d "KV namespace operations"
complete -c gw -n "__fish_use_subcommand" -a r2 -d "R2 object storage"
complete -c gw -n "__fish_use_subcommand" -a do -d "Durable Objects"
complete -c gw -n "__fish_use_subcommand" -a flag -d "Feature flags"
complete -c gw -n "__fish_use_subcommand" -a backup -d "D1 backups"
complete -c gw -n "__fish_use_subcommand" -a deploy -d "Worker deployment"
complete -c gw -n "__fish_use_subcommand" -a logs -d "Worker logs"
complete -c gw -n "__fish_use_subcommand" -a email -d "Email testing"
complete -c gw -n "__fish_use_subcommand" -a auth -d "Authentication"
complete -c gw -n "__fish_use_subcommand" -a status -d "Infrastructure status"
complete -c gw -n "__fish_use_subcommand" -a health -d "Health checks"
complete -c gw -n "__fish_use_subcommand" -a bindings -d "Show bindings"
complete -c gw -n "__fish_use_subcommand" -a git -d "Git operations"
complete -c gw -n "__fish_use_subcommand" -a gh -d "GitHub operations"
complete -c gw -n "__fish_use_subcommand" -a dev -d "Dev server"
complete -c gw -n "__fish_use_subcommand" -a test -d "Run tests"
complete -c gw -n "__fish_use_subcommand" -a build -d "Build packages"
complete -c gw -n "__fish_use_subcommand" -a check -d "Type checking"
complete -c gw -n "__fish_use_subcommand" -a lint -d "Linting"
complete -c gw -n "__fish_use_subcommand" -a ci -d "CI pipeline"
complete -c gw -n "__fish_use_subcommand" -a packages -d "Package management"
complete -c gw -n "__fish_use_subcommand" -a doctor -d "Diagnose issues"
complete -c gw -n "__fish_use_subcommand" -a whoami -d "Show identity"
complete -c gw -n "__fish_use_subcommand" -a history -d "Command history"

# db subcommands
complete -c gw -n "__fish_seen_subcommand_from db" -a list -d "List databases"
complete -c gw -n "__fish_seen_subcommand_from db" -a tables -d "List tables"
complete -c gw -n "__fish_seen_subcommand_from db" -a schema -d "Show schema"
complete -c gw -n "__fish_seen_subcommand_from db" -a query -d "Execute SQL"
complete -c gw -n "__fish_seen_subcommand_from db" -a tenant -d "Lookup tenant"

# tenant subcommands
complete -c gw -n "__fish_seen_subcommand_from tenant" -a lookup -d "Lookup tenant"
complete -c gw -n "__fish_seen_subcommand_from tenant" -a stats -d "Show statistics"
complete -c gw -n "__fish_seen_subcommand_from tenant" -a list -d "List tenants"

# cache subcommands
complete -c gw -n "__fish_seen_subcommand_from cache" -a list -d "List keys"
complete -c gw -n "__fish_seen_subcommand_from cache" -a purge -d "Purge cache"
complete -c gw -n "__fish_seen_subcommand_from cache" -a stats -d "Show stats"

# secret subcommands
complete -c gw -n "__fish_seen_subcommand_from secret" -a init -d "Initialize vault"
complete -c gw -n "__fish_seen_subcommand_from secret" -a set -d "Set secret"
complete -c gw -n "__fish_seen_subcommand_from secret" -a list -d "List secrets"
complete -c gw -n "__fish_seen_subcommand_from secret" -a delete -d "Delete secret"
complete -c gw -n "__fish_seen_subcommand_from secret" -a apply -d "Apply to worker"
complete -c gw -n "__fish_seen_subcommand_from secret" -a sync -d "Sync to worker"
complete -c gw -n "__fish_seen_subcommand_from secret" -a exists -d "Check exists"

# kv subcommands
complete -c gw -n "__fish_seen_subcommand_from kv" -a list -d "List namespaces"
complete -c gw -n "__fish_seen_subcommand_from kv" -a keys -d "List keys"
complete -c gw -n "__fish_seen_subcommand_from kv" -a get -d "Get value"
complete -c gw -n "__fish_seen_subcommand_from kv" -a put -d "Set value"
complete -c gw -n "__fish_seen_subcommand_from kv" -a delete -d "Delete key"

# r2 subcommands
complete -c gw -n "__fish_seen_subcommand_from r2" -a list -d "List buckets"
complete -c gw -n "__fish_seen_subcommand_from r2" -a ls -d "List objects"
complete -c gw -n "__fish_seen_subcommand_from r2" -a get -d "Download"
complete -c gw -n "__fish_seen_subcommand_from r2" -a put -d "Upload"
complete -c gw -n "__fish_seen_subcommand_from r2" -a rm -d "Delete"

# git subcommands
complete -c gw -n "__fish_seen_subcommand_from git" -a status -d "Show status"
complete -c gw -n "__fish_seen_subcommand_from git" -a log -d "Show history"
complete -c gw -n "__fish_seen_subcommand_from git" -a diff -d "Show changes"
complete -c gw -n "__fish_seen_subcommand_from git" -a blame -d "Show authorship"
complete -c gw -n "__fish_seen_subcommand_from git" -a show -d "Show commit"
complete -c gw -n "__fish_seen_subcommand_from git" -a add -d "Stage files"
complete -c gw -n "__fish_seen_subcommand_from git" -a commit -d "Create commit"
complete -c gw -n "__fish_seen_subcommand_from git" -a push -d "Push to remote"
complete -c gw -n "__fish_seen_subcommand_from git" -a branch -d "Manage branches"
complete -c gw -n "__fish_seen_subcommand_from git" -a stash -d "Stash changes"
complete -c gw -n "__fish_seen_subcommand_from git" -a switch -d "Switch branch"
complete -c gw -n "__fish_seen_subcommand_from git" -a save -d "Quick save"
complete -c gw -n "__fish_seen_subcommand_from git" -a sync -d "Sync with main"
complete -c gw -n "__fish_seen_subcommand_from git" -a wip -d "WIP commit"
complete -c gw -n "__fish_seen_subcommand_from git" -a undo -d "Undo commit"
complete -c gw -n "__fish_seen_subcommand_from git" -a amend -d "Amend commit"
complete -c gw -n "__fish_seen_subcommand_from git" -a reset -d "Reset (dangerous)"
complete -c gw -n "__fish_seen_subcommand_from git" -a rebase -d "Rebase (dangerous)"
complete -c gw -n "__fish_seen_subcommand_from git" -a merge -d "Merge branches"

# gh subcommands
complete -c gw -n "__fish_seen_subcommand_from gh" -a pr -d "Pull requests"
complete -c gw -n "__fish_seen_subcommand_from gh" -a issue -d "Issues"
complete -c gw -n "__fish_seen_subcommand_from gh" -a run -d "Workflow runs"
complete -c gw -n "__fish_seen_subcommand_from gh" -a api -d "Raw API access"
complete -c gw -n "__fish_seen_subcommand_from gh" -a rate-limit -d "Rate limit"

# gh pr subcommands
complete -c gw -n "__fish_seen_subcommand_from pr" -a list -d "List PRs"
complete -c gw -n "__fish_seen_subcommand_from pr" -a view -d "View PR"
complete -c gw -n "__fish_seen_subcommand_from pr" -a create -d "Create PR"
complete -c gw -n "__fish_seen_subcommand_from pr" -a checkout -d "Checkout PR"
complete -c gw -n "__fish_seen_subcommand_from pr" -a comment -d "Add comment"
complete -c gw -n "__fish_seen_subcommand_from pr" -a merge -d "Merge PR"
complete -c gw -n "__fish_seen_subcommand_from pr" -a close -d "Close PR"

# gh issue subcommands
complete -c gw -n "__fish_seen_subcommand_from issue" -a list -d "List issues"
complete -c gw -n "__fish_seen_subcommand_from issue" -a view -d "View issue"
complete -c gw -n "__fish_seen_subcommand_from issue" -a create -d "Create issue"
complete -c gw -n "__fish_seen_subcommand_from issue" -a comment -d "Add comment"
complete -c gw -n "__fish_seen_subcommand_from issue" -a close -d "Close issue"

# gh run subcommands
complete -c gw -n "__fish_seen_subcommand_from run" -a list -d "List runs"
complete -c gw -n "__fish_seen_subcommand_from run" -a view -d "View run"
complete -c gw -n "__fish_seen_subcommand_from run" -a rerun -d "Rerun jobs"
complete -c gw -n "__fish_seen_subcommand_from run" -a cancel -d "Cancel run"

# dev subcommands
complete -c gw -n "__fish_seen_subcommand_from dev" -a start -d "Start server"
complete -c gw -n "__fish_seen_subcommand_from dev" -a stop -d "Stop server"
complete -c gw -n "__fish_seen_subcommand_from dev" -a restart -d "Restart server"
complete -c gw -n "__fish_seen_subcommand_from dev" -a logs -d "View logs"
complete -c gw -n "__fish_seen_subcommand_from dev" -a status -d "Show status"

# backup subcommands
complete -c gw -n "__fish_seen_subcommand_from backup" -a list -d "List backups"
complete -c gw -n "__fish_seen_subcommand_from backup" -a create -d "Create backup"
complete -c gw -n "__fish_seen_subcommand_from backup" -a restore -d "Restore backup"
complete -c gw -n "__fish_seen_subcommand_from backup" -a download -d "Download backup"

# flag subcommands
complete -c gw -n "__fish_seen_subcommand_from flag" -a list -d "List flags"
complete -c gw -n "__fish_seen_subcommand_from flag" -a get -d "Get flag"
complete -c gw -n "__fish_seen_subcommand_from flag" -a enable -d "Enable flag"
complete -c gw -n "__fish_seen_subcommand_from flag" -a disable -d "Disable flag"

# auth subcommands
complete -c gw -n "__fish_seen_subcommand_from auth" -a check -d "Check auth"
complete -c gw -n "__fish_seen_subcommand_from auth" -a login -d "Log in"
complete -c gw -n "__fish_seen_subcommand_from auth" -a client -d "Client management"

# history subcommands
complete -c gw -n "__fish_seen_subcommand_from history" -a list -d "Show history"
complete -c gw -n "__fish_seen_subcommand_from history" -a search -d "Search history"
complete -c gw -n "__fish_seen_subcommand_from history" -a show -d "Show entry"
complete -c gw -n "__fish_seen_subcommand_from history" -a run -d "Re-run command"
complete -c gw -n "__fish_seen_subcommand_from history" -a clear -d "Clear history"

# packages subcommands
complete -c gw -n "__fish_seen_subcommand_from packages" -a list -d "List packages"
complete -c gw -n "__fish_seen_subcommand_from packages" -a info -d "Package info"
complete -c gw -n "__fish_seen_subcommand_from packages" -a current -d "Current package"
'''
