"""Zsh completion script generator."""


def generate_zsh_completion() -> str:
    """Generate zsh completion script for gw."""
    return '''#compdef gw
# Zsh completion for gw (Grove Wrap)
# Generated by gw completion zsh
# Add to ~/.zfunc/_gw or source directly

_gw() {
    local -a commands
    local -a db_commands
    local -a tenant_commands
    local -a cache_commands
    local -a secret_commands
    local -a kv_commands
    local -a r2_commands
    local -a git_commands
    local -a gh_commands
    local -a gh_pr_commands
    local -a gh_issue_commands
    local -a gh_run_commands
    local -a dev_commands
    local -a backup_commands
    local -a flag_commands
    local -a auth_commands
    local -a auth_client_commands
    local -a history_commands
    local -a packages_commands

    commands=(
        'db:Database operations'
        'tenant:Tenant lookup and management'
        'cache:Cache management'
        'secret:Secrets vault management'
        'kv:KV namespace operations'
        'r2:R2 object storage'
        'do:Durable Objects inspection'
        'flag:Feature flag management'
        'backup:D1 backup management'
        'deploy:Worker deployment'
        'logs:Worker log streaming'
        'email:Email testing'
        'auth:Authentication management'
        'status:Infrastructure status'
        'health:Service health checks'
        'bindings:Show wrangler bindings'
        'git:Git operations with safety guards'
        'gh:GitHub operations'
        'dev:Dev server management'
        'test:Run tests'
        'build:Build packages'
        'check:Type checking'
        'lint:Linting'
        'ci:Run CI pipeline locally'
        'packages:Package management'
        'doctor:Diagnose common issues'
        'whoami:Show identity and context'
        'history:Command history'
    )

    db_commands=(
        'list:List databases'
        'tables:List tables in a database'
        'schema:Show table schema'
        'query:Execute SQL query'
        'tenant:Look up tenant info'
    )

    tenant_commands=(
        'lookup:Look up tenant by subdomain/email/id'
        'stats:Show tenant statistics'
        'list:List all tenants'
    )

    cache_commands=(
        'list:List cached keys'
        'purge:Purge cache keys'
        'stats:Show cache statistics'
    )

    secret_commands=(
        'init:Initialize secrets vault'
        'set:Set a secret value'
        'list:List secret names'
        'delete:Delete a secret'
        'apply:Apply secret to worker'
        'sync:Sync secrets to worker'
        'exists:Check if secret exists'
    )

    kv_commands=(
        'list:List KV namespaces'
        'keys:List keys in namespace'
        'get:Get a value'
        'put:Set a value'
        'delete:Delete a key'
    )

    r2_commands=(
        'list:List buckets'
        'ls:List objects in bucket'
        'get:Download object'
        'put:Upload object'
        'rm:Delete object'
    )

    git_commands=(
        'status:Show repository status'
        'log:Show commit history'
        'diff:Show changes'
        'blame:Show line-by-line authorship'
        'show:Show commit details'
        'add:Stage files'
        'commit:Create commit'
        'push:Push to remote'
        'branch:Manage branches'
        'stash:Stash changes'
        'switch:Switch branches'
        'save:Quick save (add all + WIP commit)'
        'sync:Fetch, rebase, push'
        'wip:WIP commit'
        'undo:Undo last commit'
        'amend:Amend last commit'
        'reset:Reset changes (dangerous)'
        'rebase:Rebase (dangerous)'
        'merge:Merge branches'
    )

    gh_commands=(
        'pr:Pull request operations'
        'issue:Issue operations'
        'run:Workflow run operations'
        'api:Raw API access'
        'rate-limit:Show rate limit status'
    )

    gh_pr_commands=(
        'list:List pull requests'
        'view:View PR details'
        'create:Create a PR'
        'checkout:Check out PR branch'
        'comment:Add comment'
        'merge:Merge PR'
        'close:Close PR'
    )

    gh_issue_commands=(
        'list:List issues'
        'view:View issue details'
        'create:Create an issue'
        'comment:Add comment'
        'close:Close issue'
    )

    gh_run_commands=(
        'list:List workflow runs'
        'view:View run details'
        'rerun:Rerun failed jobs'
        'cancel:Cancel a run'
    )

    dev_commands=(
        'start:Start dev server'
        'stop:Stop dev server'
        'restart:Restart dev server'
        'logs:View server logs'
        'status:Show running servers'
    )

    backup_commands=(
        'list:List backups'
        'create:Create a backup'
        'restore:Restore from backup'
        'download:Download backup file'
    )

    flag_commands=(
        'list:List feature flags'
        'get:Get flag status'
        'enable:Enable a flag'
        'disable:Disable a flag'
    )

    auth_commands=(
        'check:Check authentication status'
        'login:Log in to Cloudflare'
        'client:OAuth client management'
    )

    auth_client_commands=(
        'create:Register new OAuth client'
        'list:List registered clients'
        'info:Get client details'
        'rotate:Rotate client secret'
        'delete:Delete a client'
        'setup:Full setup wizard'
    )

    history_commands=(
        'list:Show command history'
        'search:Search history'
        'show:Show entry details'
        'run:Re-run a command'
        'clear:Clear history'
    )

    packages_commands=(
        'list:List packages'
        'info:Show package info'
        'current:Show current package'
    )

    _arguments -C \\
        '--help[Show help]' \\
        '--json[Output as JSON]' \\
        '1: :->command' \\
        '*:: :->args'

    case $state in
        command)
            _describe -t commands 'gw commands' commands
            ;;
        args)
            case $words[1] in
                db)
                    _describe -t commands 'db commands' db_commands
                    ;;
                tenant)
                    _describe -t commands 'tenant commands' tenant_commands
                    ;;
                cache)
                    _describe -t commands 'cache commands' cache_commands
                    ;;
                secret)
                    _describe -t commands 'secret commands' secret_commands
                    ;;
                kv)
                    _describe -t commands 'kv commands' kv_commands
                    ;;
                r2)
                    _describe -t commands 'r2 commands' r2_commands
                    ;;
                git)
                    _describe -t commands 'git commands' git_commands
                    ;;
                gh)
                    case $words[2] in
                        pr)
                            _describe -t commands 'gh pr commands' gh_pr_commands
                            ;;
                        issue)
                            _describe -t commands 'gh issue commands' gh_issue_commands
                            ;;
                        run)
                            _describe -t commands 'gh run commands' gh_run_commands
                            ;;
                        *)
                            _describe -t commands 'gh commands' gh_commands
                            ;;
                    esac
                    ;;
                dev)
                    _describe -t commands 'dev commands' dev_commands
                    ;;
                backup)
                    _describe -t commands 'backup commands' backup_commands
                    ;;
                flag)
                    _describe -t commands 'flag commands' flag_commands
                    ;;
                auth)
                    case $words[2] in
                        client)
                            _describe -t commands 'auth client commands' auth_client_commands
                            ;;
                        *)
                            _describe -t commands 'auth commands' auth_commands
                            ;;
                    esac
                    ;;
                history)
                    _describe -t commands 'history commands' history_commands
                    ;;
                packages)
                    _describe -t commands 'packages commands' packages_commands
                    ;;
            esac
            ;;
    esac
}

_gw "$@"
'''
